# Generated by Django 5.2.5 on 2025-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_labtest_labtestbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbooking',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
